{% set name = "stable-baselines3" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stable_baselines3-{{ version }}.tar.gz
  sha256: cd90d12d9ee0d9584053f12215c1682b313be4e3a8d8007739319799c3d2c071

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - gymnasium >=0.29.1,<1.3.0
    - numpy >=1.20,<3.0
    - pytorch >=2.3,<3.0
    - cloudpickle
    - pandas
    - matplotlib-base

test:
  imports:
    - stable_baselines3
    - stable_baselines3.a2c
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DLR-RM/stable-baselines3
  summary: Pytorch version of Stable Baselines, implementations of reinforcement learning algorithms.
  license: MIT
  license_file: LICENSE
  doc_url: https://stable-baselines3.readthedocs.io/
  dev_url: https://github.com/DLR-RM/stable-baselines3

extra:
  recipe-maintainers:
    - YYYasin19
    - cyprienc
    - pavelzw
