{% set name = "stable-baselines3" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stable_baselines3-{{ version }}.tar.gz
  sha256: d30241afdfd092ffd85b64b3308670c72fc4834419dd668faf50096fcd5ce6ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cloudpickle
    - gym =0.21
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.7
    - pytorch >=1.8.1

test:
  imports:
    - stable_baselines3
    - stable_baselines3.a2c
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DLR-RM/stable-baselines3
  summary: Pytorch version of Stable Baselines, implementations of reinforcement learning algorithms.
  license: MIT
  license_file: LICENSE
  doc_url: https://stable-baselines3.readthedocs.io/
  dev_url: https://github.com/DLR-RM/stable-baselines3

extra:
  recipe-maintainers:
    - cyprienc
