{% set name = "stable-baselines3" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stable_baselines3-{{ version }}.tar.gz
  sha256: 08297aee3dffab85174cd48f652a6e4020008e463d4e86d659b86c918f3f57bb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cloudpickle
    - gym >=0.17
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.6
    - pytorch >=1.4.0

test:
  imports:
    - stable_baselines3
    - stable_baselines3.a2c
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DLR-RM/stable-baselines3
  summary: Pytorch version of Stable Baselines, implementations of reinforcement learning algorithms.
  license: MIT
  license_file: LICENSE
  doc_url: https://stable-baselines3.readthedocs.io/
  dev_url: https://github.com/DLR-RM/stable-baselines3

extra:
  recipe-maintainers:
    - cyprienc
